version: '2'
name: media-server
services:
  # openvpn-as:
  #   image: ghcr.io/linuxserver/openvpn-as
  #   container_name: openvpn-as
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - INTERFACE=eth0 #optional
  #   volumes:
  #     - <path to data>:/config
  #   ports:
  #     - 943:943
  #     - 9443:9443
  #     - 1194:1194/udp
  #     # qbittorrent ports
  #     - 5080:5080
  #     - 6881:6881
  #     - 6881:6881/udp
  #     # prowlarr ports
  #     - 9696:9696
  #   restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # depends_on:
    #   - openvpn-as
    # network_mode: service:openvpn-as # Comment this line if vpn is disabled
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    # Uncomment below ports if VPN is disabled.
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - AUTO_UPDATE=true #optional
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - radarr-config:/config
      - radarr-movies:/movies
      - torrent-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - sonarr-config:/config
      - sonarr-tvseries:/tv
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - bazarr-config:/config
      - bazarr-movies:/movies
      - torrent-downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - lidarr-config:/config
      - lidarr-music:/music
      - torrent-downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    # # Comment this if vpn is disabled
    # depends_on:
    #   - vpn
    # network_mode: service:vpn # Comment this line if vpn is disabled
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - prowlarr-config:/config
    # Uncomment below ports if VPN is disabled.
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - plex-config:/config
      - sonarr-tvseries:/tv
      - radarr-movies:/movies
      - lidarr-music:/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - mynetwork
    environment:
        - LOG_LEVEL=debug
        - TZ=Brazil
    ports:
        - 5055:5055
    volumes:
        - jellyfin-config:/app/config
    restart: unless-stopped

volumes:
  qbittorrent-config:
  torrent-downloads:
  jackett-config:
  jackett-blackhole:
  radarr-config:
  radarr-movies:
  sonarr-config:
  sonarr-tvseries:
  bazarr-config:
  bazarr-movies:
  lidarr-config:
  lidarr-music:
  prowlarr-config:
  jellyfin-config:
  ombi-config:
  tx-config:
  tx-watch:

networks:
  mynetwork:
    external: true