version: '2.1'
name: media-server
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - WEBUI_PORT=8080
    volumes:
      - /mnt/btrfs/docker/media-center/qbittorrent-config:/config
      - /mnt/btrfs/docker/media-center/torrent-downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/btrfs/docker/media-center/prowlar-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - /mnt/btrfs/docker/media-center/radarr-config:/config
      - /mnt/btrfs/docker/media-center/md-movies:/movies
      - /mnt/btrfs/docker/media-center/torrent-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - /mnt/btrfs/docker/media-center/sonarr-config:/config
      - /mnt/btrfs/docker/media-center/md-tvseries:/tvseries
      - /mnt/btrfs/docker/media-center/torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/btrfs/docker/media-center/bazarr-config:/config
      - /mnt/btrfs/docker/media-center/md-movies:/movies
      - /mnt/btrfs/docker/media-center/torrent-downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - /mnt/btrfs/docker/media-center/lidarr-config:/config
      - /mnt/btrfs/docker/media-center/md-music:/music
      - /mnt/btrfs/docker/media-center/torrent-downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/btrfs/docker/media-center/plex/plex-config>:/config
      - /mnt/btrfs/docker/media-center/md-movies:/movies
      - /mnt/btrfs/docker/media-center/md-tvseries:/tvseries
      - /mnt/btrfs/docker/media-center/md-music:/music
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - mynetwork
    environment:
        - LOG_LEVEL=debug
        - TZ=Brazil
    ports:
        - 5055:5055
    volumes:
        - /mnt/btrfs/docker/media-center/plex-config:/app/config
    restart: unless-stopped

volumes:
  qbittorrent-config:
  prowlar-config:
  radarr-config:
  bazarr-config:
  lidarr-config:
  sonarr-config:
  plex-config:
  torrent-downloads:
  md-movies:
  md-tvseries:
  md-music:
  tx-config:
  tx-watch:

networks:
  mynetwork:
    external: true